##
# Properties that tend to vary with each deployment
#

## Custom path variables. Set these per installation.
# 1) Base of the whole app, not just the Java app
app.base=${user.home}/GitHub/brew-pilot
# 2) Directory from which static files can be served directly
static.content=${app.base}/staticContent

# BCrypt hash of the guest and admin passwords (values beginning "$2"). These must be set. Use
# a tool such as https://bcrypt-generator.com/ to generate the hash code for each password.
# The following hashes are for temporary passwords "guest" and "admin" respectively.
pwdhash.guest=$2y$04$ZuztduDisdh4KBxSREaxCOrbzRxYuSweQxseZ7fPMa5v3us1aolMa
pwdhash.admin=$2y$04$iwY4S/mX48AaoAUG8.8hieVJJJkKLWvoQoReOeXqdAZu7GCYe5EIi


# Set to true to enable testing without real chambers. Default is false.
dummy.chambers=true

# Two comma separated values. The first part must be "classpath:/static/". The second part should
# be set to a directory from which static files can be served directly.
spring.web.resources.static-locations=classpath:/static/, file:${static.content}

# Location of JSON data files that serve as persistent storage and which may be served directly
# to the front end. Must be consistent with second part of spring.web.resources.static-locations
dataDir=${static.content}/data

# Enable or disable Undertow access logging explicitly
server.undertow.accesslog.enabled=false
# Relative path to write access logs into the ./logs folder under project root
server.undertow.accesslog.dir=./logs
server.undertow.accesslog.directory=./logs
# Explicitly set naming format
server.undertow.accesslog.prefix=access_log.
server.undertow.accesslog.suffix=log
server.undertow.accesslog.pattern=common
server.undertow.accesslog.rotate=true

# The application and the logging framework may attempt to send email.
# Note: Commenting-out either of the following two properties will effectively disable emailing.
#mail.to=easleydp@gmail.com
#mail.from=easleydp@gmail.com
spring.mail.username=easleydp@gmail.com
spring.mail.host=smtp.gmail.com
spring.mail.password=
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=10000

# Your DNS provider's dynamic update URL. Comment out / leave blank to not attempt.
app.public-ip-change.dns-update-url=https://freedns.afraid.org/dynamic/update.php?MDdaSTZtbHBtbjZpSHRzcFQzUVd2dGc0OjI1NDYxNjg1

logging.config=file:./logback-spring.xml

## End